import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

import fs from "fs";
import path from "path";

if (prod) {
	await context.rebuild();
} else {
	await context.watch();
}

// Auto-copy to target vault
const targetDir = "C:\\hermes-memory\\.obsidian\\plugins\\multi-vault-navigator";
if (!fs.existsSync(targetDir)) {
	fs.mkdirSync(targetDir, { recursive: true });
}
try {
	fs.copyFileSync("main.js", path.join(targetDir, "main.js"));
	fs.copyFileSync("manifest.json", path.join(targetDir, "manifest.json"));
	fs.copyFileSync("styles.css", path.join(targetDir, "styles.css"));
	console.log(`\n✅ Successfully copied build files to: ${targetDir}`);
} catch (e) {
	console.error("Failed to copy files to target vault:", e);
}

if (prod) {
	process.exit(0);
}
